config/routes.rb
Rails.application.routes.draw do


# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, :events

  root 'static_pages#home'
  delete '/join', to: 'events#leave'
  get '/join', to: 'events#join'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'login_sessions#new'
  post '/login', to: 'login_sessions#create'
  delete '/logout', to: 'login_sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :host, class_name: "User"
	has_many :guest_lists
	has_many :guests, through: :guest_lists, source: :user 

	scope :past, -> {where("date < ?", Time.now)}
	scope :future, -> {where("date > ?", Time.now)}

    



end

app/models/guest_list.rb
class GuestList < ApplicationRecord
	belongs_to :user
	belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord

	has_many :hosted_events, class_name: "Event", foreign_key: "host_id"
	has_many :guest_lists
	has_many :attended_events, through: :guest_lists, source: :event
	before_save {self.email.downcase!}


	validates :email, presence: :true 
	validates :name, presence: :true 

   


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include LoginSessionsHelper
  include EventsHelper


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :logged_in_user?, only: [:create, :new, :destroy, :join]


  def index
  	@events = Event.all 
  end

  def new
  	@event = current_user.hosted_events.new
  end

  def create
  	@event = current_user.hosted_events.new(event_params)
  	if @event.save 
      @event.guests << current_user 
  		flash[:success] = 'Event Created Successfully'
  		redirect_to @event
  	else
  		flash.now[:danger] = 'Event Creation Failed'
  		render 'new'
  	end
  end

  def show
  	@event = Event.find(params[:id])
    @guests = @event.guests
  end

  def join
    @event = Event.find(params[:id])
    if !attending?(@event)
      @event.guests << current_user
      flash[:sucess] = 'You have joined the event'
      redirect_to @event 
    else
      flash[:danger] = 'You are already attending this event'
      redirect_back fallback_location: root_path
    end

  end

  def destroy
  end

  def attending?(event)
    if event.guests.include?(current_user)
      return true
    else
      return false
    end
  end

  private

  def event_params
  	params.require(:event).permit(:name, :location, :date)
  end

  def logged_in_user?
  	unless logged_in?
  		flash[:danger] = 'Please Log In First'
  		redirect_to login_url
  	end
  end


 

  



end

app/controllers/login_sessions_controller.rb
class LoginSessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:loginsession][:email].downcase)
		if user 
			log_in(user)
			flash[:success] = 'You have been successfully logged in'
			redirect_to user_url(user)
		else
			flash.now[:danger] = 'User not found'
			render 'new'
	    end
	end

	def destroy 
		log_out
		flash[:success] = 'Successfully logged out'
		redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		log_in(@user)
  		flash[:sucess] = "Signup Successful - Welcome #{@user.name}"
  		redirect_to @user
  	else
  		flash.now[:danger] = 'Invalid Input - Signup Failed'
  		render 'new'
  	end
  end
  
  def show
  	@user = User.find(params[:id])
  	
  	#Hosted
  	@hosted_events = @user.hosted_events.past
  	#Hosting
  	@hosting_events = @user.hosted_events.future
  	#Attended
    @attended_events = @user.attended_events.past
  	#Attending
  	@attending_events = @user.attended_events.future
  end

  def destroy
  end

  private 

   def user_params 
   	params.require(:user).permit(:email,:name)
   end


end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/events_helper.rb
module EventsHelper



end

app/helpers/login_sessions_helper.rb
module LoginSessionsHelper


	def log_in(user)
		session[:user_id] = user.id
	end

	def logged_in?
		!current_user.nil?
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def log_out
		@current_user = nil
		session[:user_id] = nil
	end



end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<li>
	<%=link_to event.name, event%> 
   </br>
	<%=event.location%>
	</br>
	<%=event.date%>
    </br>
    <%= link_to 'Join Event', join_path(id: event.id) if logged_in? %>

</li>

app/views/events/_guest.html.erb
<%@guests.each do |guest| %>
<li>
	<%=guest.name%>
	<%=guest.email%>
</li>
<%end%>

app/views/events/_hosted_events.html.erb
<li>
	<%=event.name%>
	<%=event.location%>
	<%=event.date%>
</li>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/index.html.erb
<%if @events %>
<ol>
  <%= render @events%>
</ol>
<%end%>

app/views/events/new.html.erb
<h1>Events#new</h1>

<%= form_for(@event) do |f| %>
  <%=f.label :name %>
  <%=f.text_field :name%>

  <%=f.label :location %>
  <%=f.text_field :location %>

  <%=f.label :date%>
  <%=f.datetime_local_field :date %>

  <%=f.submit "Create Event" %>
<%end%>

app/views/events/show.html.erb
<h1>Events#Show</h1>
Event: <%=@event.name%>
</br>
Where: <%=@event.location%>
</br>
When: <%=@event.date%>
</br>
Hosted by: <%=@event.host.name%>
</br>
</br>

<b>Guests:</b>
<% if @event.guests.any? %>
 <%= render 'guest' %>
 <% else %>
  </br>
  No Guests Currently Attending This Event
 <%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= link_to 'Home', root_url %>
  	<%= render 'shared/login_status' %>
  	<% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
     <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/login_sessions/new.html.erb
<h1>LoginSessions#New</h1>

<%= form_for(:loginsession, url: login_path) do |f| %>
	<%= f.label :email %>
	<%= f.email_field :email %>
	<%= f.submit 'Log In' %>
<%end%>

app/views/shared/_login_status.html.erb
<% if logged_in? %>
 <%= link_to current_user.name, user_url(current_user) %>
 <%= link_to 'Log Out', logout_path, method: :delete %>
 <%else%>
 <%= link_to 'Sign Up', signup_path %>
 <%= link_to 'Log In', login_path %>
<%end%>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Private Events</p>
<%if logged_in? %>
  <%= link_to 'Create Event', new_event_path %>
<%end%>
<%= link_to 'View All Events', events_path %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>

<%= form_for(@user) do |f| %>
  <%= f.label :email %>
  <%= f.email_field :email %>
</br>

  <%= f.label :name %>
  <%= f.text_field :name %>
</br>

  <%= f.submit 'Sign Up' %>

  <% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
</br>
<p><%=@user.email%></p>
<p><%=@user.name%></p>



<% if @hosting_events %>
    <h4> Events <%=@user.name%> is hosting: </h4>
	<ol>
	  <%= render @hosting_events %>
	</ol>
<%end%>

<% if @hosted_events %>
    <h4> Events <%=@user.name%> hosted: </h4>
	<ol>
	  <%= render @hosted_events %>
	</ol>
<%end%>



<% if @attending_events %>
    <h4> Events <%=@user.name%> is attending: </h4>
	<ol>
	  <%= render @attending_events %>
	</ol>
<%end%>

<% if @attended_events %>
    <h4> Events <%=@user.name%> has attended: </h4>
	<ol>
	  <%= render @attended_events %>
	</ol>
<%end%>